---
- name: Docker | Check installed
  stat: path=/usr/bin/docker
  register: docker_path

- name: Docker | Install
  shell: /usr/bin/curl -sSL https://get.docker.com/ | sh
  sudo: yes
  when: docker_path.stat.exists == False

- name: Docker | create docker group
  group: name=docker state=present
  when: docker_group == True

- name: Docker | add user to docker group
  user: name={{ docker_user }} group=docker
  when: docker_user is defined
